---
# tasks file for ambari_common
- name: Install libselinux-python
  yum: name=libselinux-python state=latest

- include: passwd_less_ssh.yml

# 
# ambari uses socket.getfqdn() to find the hostname. with 'localhost.localdomain'
# in '/etc/hosts' this function will report the hostname as 'localhost.localdomain'
# rather than 'node1' as would be expected.  other functions like socket.gethostname()
# will always return 'node1' as expected.  ambari needs to see 'node1' to be able to
# communicate between the master and agents.

- name: Remove ipv4 'localhost.localdomain' from /etc/hosts
  lineinfile: dest=/etc/hosts state=absent regexp="^127.0.0.1(.*)localdomain(.*)$"

- name: Remove ipv6 'localhost.localdomain' from /etc/hosts
  lineinfile: dest=/etc/hosts state=absent regexp="^::1(.*)localdomain(.*)$"

- name: Add localhost to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1   localhost"

- name: Download HDP repo
  get_url: url="{{ rhel_ambari_install_url }}" dest=/etc/yum.repos.d/

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present

- name: Clean yum
  shell: yum clean all

- name: install ntp
  yum: name=ntp state=present

- name: Ensure ntp is running and enabled
  service: name=ntpd state=started enabled=yes

- name: Ensure iptables is stopped and is not running at boot time.
  service: name=iptables state=stopped enabled=no
