#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
#
# produces network traffic
#
- hosts: source
  become: yes
  vars:
    pcap_replay_interface: "enp0s8"
  roles:
    - role: pcap_replay

#
# consumes network traffic
#
- hosts: sink
  become: yes
  vars:
      dpdk_device: ["00:08.0"]
      dpdk_target: "x86_64-native-linuxapp-gcc"
      num_huge_pages: 512
      pcapture_portmask: 0xf
      pcapture_topic: pcap
      kafka_broker_url: localhost:9092
  roles:
    - role: librdkafka
    - role: kafka-broker
    - role: packet-capture
