---
- name: Install flume configurations
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: flume-snort.conf, dest: /etc/flume/conf/flume-snort.conf }

- name: Set kafka broker in flume
  lineinfile: >
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { dest: /etc/flume/conf/flume-snort.conf,
        regexp: '^snort\.sinks\.kafka-sink\.brokerList.*$',
        line: 'snort.sinks.kafka-sink.brokerList = {{ kafka_broker_url }}' }

- name: Set kafka topics in flume
  lineinfile: >
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { dest: /etc/flume/conf/flume-snort.conf,
        regexp: '^snort\.sinks\.kafka-sink\.topic.*$',
        line: 'snort.sinks.kafka-sink.topic = {{ snort_topic }}'}
