---
- name: Install flume configurations
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: flume-bro.conf.template, dest: /etc/flume/conf/flume-bro-conn.conf }
    - { src: flume-bro.conf.template, dest: /etc/flume/conf/flume-bro-dns.conf }
    - { src: flume-bro.conf.template, dest: /etc/flume/conf/flume-bro-software.conf }

- name: Set kafka broker in flume
  lineinfile: >
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { dest: /etc/flume/conf/flume-bro-conn.conf,
        regexp: '^bro-conn\.sinks\.kafka-sink\.brokerList.*$',
        line: 'bro-conn.sinks.kafka-sink.brokerList = {{ kafka_broker_url }}' }
    - { dest: /etc/flume/conf/flume-bro-dns.conf,
        regexp: '^bro-dns\.sinks\.kafka-sink\.brokerList.*$',
        line: 'bro-dns.sinks.kafka-sink.brokerList = {{ kafka_broker_url }}' }
    - { dest: /etc/flume/conf/flume-bro-software.conf,
        regexp: '^bro-software\.sinks\.kafka-sink\.brokerList.*$',
        line: 'bro-software.sinks.kafka-sink.brokerList = {{ kafka_broker_url }}' }

- name: Set kafka topics in flume
  lineinfile: >
    dest="{{ item.dest }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
  with_items:
    - { dest: /etc/flume/conf/flume-bro-conn.conf,
        regexp: '^bro-conn\.sinks\.kafka-sink\.topic.*$',
        line: 'bro-conn.sinks.kafka-sink.topic = {{ bro_conn_topic }}' }
    - { dest: /etc/flume/conf/flume-bro-dns.conf,
        regexp: '^bro-dns\.sinks\.kafka-sink\.topic.*$',
        line: 'bro-dns.sinks.kafka-sink.topic = {{ bro_dns_topic }}' }
    - { dest: /etc/flume/conf/flume-bro-software.conf,
        regexp: '^bro-software\.sinks\.kafka-sink\.topic.*$',
        line: 'bro-software.sinks.kafka-sink.topic = {{ bro_software_topic }}' }
