---
- name: Download librdkafka
  get_url:
    url: https://github.com/edenhill/librdkafka/archive/v0.9.0.tar.gz
    dest: /tmp/librdkafka-0.9.0.tar.gz

- name: Extract librdkafka tarball
  unarchive:
    src: /tmp/librdkafka-0.9.0.tar.gz
    dest: /tmp
    copy: no
    creates: /tmp/librdkafka-0.9.0

- name: Compile and install librdkafka
  shell: "{{ item }}"
  args:
    chdir: /tmp/librdkafka-0.9.0
    creates: /usr/local/lib/librdkafka.so
  with_items:
    - ./configure
    - make
    - make install
