---
- name: Install prerequisites
  yum: name={{ item }}
  with_items:
    - libselinux-python
    - cmake
    - make
    - gcc
    - gcc-c++
    - flex
    - bison
    - libpcap
    - libpcap-devel
    - openssl-devel
    - python-devel
    - swig
    - zlib-devel

- include: librdkafka.yml

- include: bro.yml

- include: bro-plugin-kafka.yml

- name: Update bro configuration
  shell: /usr/local/bro/bin/broctl install

- name: Start bro
  shell: /usr/local/bro/bin/broctl start
