name: "pcap-local"
config:
    topology.workers: 1

components:
    -   id: "parser"
        className: "org.apache.metron.parsing.parsers.PcapParser"
        configMethods:
            -   name: "withTsPrecision"
                args: ["MICRO"]
    -   id: "geoEnrichmentAdapter"
        className: "org.apache.metron.integration.util.mock.MockGeoAdapter"
    -   id: "geoEnrichment"
        className: "org.apache.metron.domain.Enrichment"
        properties:
            -   name: "name"
                value:  "geo"
            -   name: "fields"
                value: ["ip_src_addr", "ip_dst_addr"]
            -   name: "adapter"
                ref: "geoEnrichmentAdapter"
    -   id: "hostEnrichmentAdapter"
        className: "org.apache.metron.enrichment.adapters.host.HostFromJSONListAdapter"
        constructorArgs:
            - '${org.apache.metron.enrichment.host.known_hosts}'
    -   id: "hostEnrichment"
        className: "org.apache.metron.domain.Enrichment"
        properties:
            -   name: "name"
                value:  "host"
            -   name: "fields"
                value: ["ip_src_addr", "ip_dst_addr"]
            -   name: "adapter"
                ref: "hostEnrichmentAdapter"
    -   id: "enrichments"
        className: "java.util.ArrayList"
        configMethods:
            -   name: "add"
                args:
                    - ref: "geoEnrichment"
            -   name: "add"
                args:
                    - ref: "hostEnrichment"
    -   id: "indexAdapter"
        className: "org.apache.metron.indexing.adapters.ESTimedRotatingAdapter"
    -   id: "metricConfig"
        className: "org.apache.commons.configuration.BaseConfiguration"
        configMethods:
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.reporter.graphite"
                    - "${org.apache.metron.metrics.reporter.graphite}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.reporter.console"
                    - "${org.apache.metron.metrics.reporter.console}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.reporter.jmx"
                    - "${org.apache.metron.metrics.reporter.jmx}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.graphite.address"
                    - "${org.apache.metron.metrics.graphite.address}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.graphite.port"
                    - "${org.apache.metron.metrics.graphite.port}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.TelemetryParserBolt.acks"
                    - "${org.apache.metron.metrics.TelemetryParserBolt.acks}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.TelemetryParserBolt.emits"
                    - "${org.apache.metron.metrics.TelemetryParserBolt.emits}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.TelemetryParserBolt.fails"
                    - "${org.apache.metron.metrics.TelemetryParserBolt.fails}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.GenericEnrichmentBolt.acks"
                    - "${org.apache.metron.metrics.GenericEnrichmentBolt.acks}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.GenericEnrichmentBolt.emits"
                    - "${org.apache.metron.metrics.GenericEnrichmentBolt.emits}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.GenericEnrichmentBolt.fails"
                    - "${org.apache.metron.metrics.GenericEnrichmentBolt.fails}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.TelemetryIndexingBolt.acks"
                    - "${org.apache.metron.metrics.TelemetryIndexingBolt.acks}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.TelemetryIndexingBolt.emits"
                    - "${org.apache.metron.metrics.TelemetryIndexingBolt.emits}"
            -   name: "setProperty"
                args:
                    - "org.apache.metron.metrics.TelemetryIndexingBolt.fails"
                    - "${org.apache.metron.metrics.TelemetryIndexingBolt.fails}"
    -   id: "hbaseConfig"
        className: "org.apache.metron.hbase.TupleTableConfig"
        configMethods:
            -   name: "withFields"
                args:
                    - "${bolt.hbase.table.fields}"
            -   name: "withTable"
                args:
                    - "${bolt.hbase.table.name}"
            -   name: "withRowKeyField"
                args:
                    - "${bolt.hbase.table.key.tuple.field.name}"
            -   name: "withTimestampField"
                args:
                    - "${bolt.hbase.table.timestamp.tuple.field.name}"
            -   name: "withBatch"
                args:
                    - ${bolt.hbase.enable.batching}
spouts:
    -   id: "testingSpout"
        className: "org.apache.metron.test.spouts.GenericInternalTestSpout"
        parallelism: 1
        configMethods:
            -   name: "withBinaryConverter"
                args:
                    - "${pcap.binary.converter}"
            -   name: "withFilename"
                args:
                    - "${input.path}SampleInput/PCAPExampleOutput"
            -   name: "withRepeating"
                args:
                    - ${testing.repeating}

bolts:
    -   id: "hbaseBolt"
        className: "org.apache.metron.hbase.HBaseBolt"
        constructorArgs:
            - ref: "hbaseConfig"
            - "${kafka.zk}"
        configMethods:
            -   name: "withConnector"
                args:
                    - "${hbase.connector.impl}"
    -   id: "parserBolt"
        className: "org.apache.metron.bolt.PcapParserBolt"
        configMethods:
            -   name: "withMessageParser"
                args:
                    - ref: "parser"
            -   name: "withEnrichments"
                args:
                    - ref: "enrichments"
    -   id: "indexingBolt"
        className: "org.apache.metron.indexing.TelemetryIndexingBolt"
        configMethods:
            -   name: "withIndexIP"
                args:
                    - "${es.ip}"
            -   name: "withIndexPort"
                args:
                    - ${es.port}
            -   name: "withClusterName"
                args:
                    - "${es.clustername}"
            -   name: "withIndexName"
                args:
                    - "pcap_index"
            -   name: "withIndexTimestamp"
                args:
                    - "yyyy.MM.dd.hh"
            -   name: "withDocumentName"
                args:
                    - "pcap_doc"
            -   name: "withBulk"
                args:
                    - 1
            -   name: "withIndexAdapter"
                args:
                    - ref: "indexAdapter"
            -   name: "withMetricConfiguration"
                args:
                    - ref: "metricConfig"
    -   id: "errorIndexingBolt"
        className: "org.apache.metron.indexing.TelemetryIndexingBolt"
        configMethods:
            -   name: "withIndexIP"
                args:
                    - "${es.ip}"
            -   name: "withIndexPort"
                args:
                    - ${es.port}
            -   name: "withClusterName"
                args:
                    - "${es.clustername}"
            -   name: "withIndexName"
                args:
                    - "error"
            -   name: "withIndexTimestamp"
                args:
                    - "yyyy.MM"
            -   name: "withDocumentName"
                args:
                    - "pcap_error"
            -   name: "withBulk"
                args:
                    - 1
            -   name: "withIndexAdapter"
                args:
                    - ref: "indexAdapter"
            -   name: "withMetricConfiguration"
                args:
                    - ref: "metricConfig"
    -   id: "geoEnrichmentBolt"
        className: "org.apache.metron.enrichment.bolt.GenericEnrichmentBolt"
        configMethods:
            -   name: "withEnrichment"
                args:
                    - ref: "geoEnrichment"
            -   name: "withMaxCacheSize"
                args: [10000]
            -   name: "withMaxTimeRetain"
                args: [10]
    -   id: "hostEnrichmentBolt"
        className: "org.apache.metron.enrichment.bolt.GenericEnrichmentBolt"
        configMethods:
            -   name: "withEnrichment"
                args:
                    - ref: "hostEnrichment"
            -   name: "withMaxCacheSize"
                args: [10000]
            -   name: "withMaxTimeRetain"
                args: [10]
    -   id: "joinBolt"
        className: "org.apache.metron.enrichment.bolt.EnrichmentJoinBolt"
        configMethods:
        -   name: "withEnrichments"
            args:
                - ref: "enrichments"
        -   name: "withMaxCacheSize"
            args: [10000]
        -   name: "withMaxTimeRetain"
            args: [10]

streams:
    -   name: "spout -> parser"
        from: "testingSpout"
        to: "parserBolt"
        grouping:
            type: SHUFFLE
    -   name: "parser -> hbase"
        from: "parserBolt"
        to: "hbaseBolt"
        grouping:
            streamId: "raw"
            type: FIELDS
            args: ["key"]
    -   name: "parser -> host"
        from: "parserBolt"
        to: "hostEnrichmentBolt"
        grouping:
            streamId: "host"
            type: FIELDS
            args: ["key"]
    -   name: "parser -> geo"
        from: "parserBolt"
        to: "geoEnrichmentBolt"
        grouping:
            streamId: "geo"
            type: FIELDS
            args: ["key"]
    -   name: "parser -> join"
        from: "parserBolt"
        to: "joinBolt"
        grouping:
            streamId: "message"
            type: FIELDS
            args: ["key"]
    -   name: "geo -> join"
        from: "geoEnrichmentBolt"
        to: "joinBolt"
        grouping:
            streamId: "geo"
            type: FIELDS
            args: ["key"]
    -   name: "host -> join"
        from: "hostEnrichmentBolt"
        to: "joinBolt"
        grouping:
            streamId: "host"
            type: FIELDS
            args: ["key"]
    -   name: "join -> indexing"
        from: "joinBolt"
        to: "indexingBolt"
        grouping:
            streamId: "message"
            type: FIELDS
            args: ["key"]
    -   name: "parser -> errors"
        from: "parserBolt"
        to: "errorIndexingBolt"
        grouping:
            streamId: "error"
            type: SHUFFLE
    -   name: "indexing -> errors"
        from: "indexingBolt"
        to: "errorIndexingBolt"
        grouping:
            streamId: "error"
            type: SHUFFLE
